spring:
  cache:
    cache-names: redisCache
    redis:
      cache-null-values: true
      key-prefix: redisCache_
      time-to-live: 600000ms
      use-key-prefix: true
    type: redis
  redis:
    database: 0
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
    password: 123qweasd
    port: 6379
    timeout: 1000
