version: "3"
services:
  server-provider-8081:
    restart: always
    build: ./
    ports:
      - 8081:8080
    networks:
      - nacos_net
  server-provider-8082:
    restart: always
    build: ./
    ports:
      - 8082:8080
    networks:
      - nacos_net
  server-provider-8083:
    restart: always
    build: ./
    ports:
      - 8083:8080
    networks:
      - nacos_net


networks:
  nacos_net:
    driver: macvlan
    ipam:
      config:
        - subnet: 192.168.1.0/24
        - gateway: 192.168.1.1
