version: '3'
services:
  # nacos-server服务注册与发现，配置中心服务
  docker-nacos-server:
    image: nacos/nacos-server:1.0.1
    container_name: nacos-server-8881
    ports:
      - "8881:8848"
    networks:
      - nacos_net
    restart: on-failure
    privileged: true
    environment:
      PREFER_HOST_MODE: ip #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      NACOS_SERVER_IP: 192.168.0.103 #多网卡情况下，指定ip或网卡
      NACOS_SERVERS: 192.168.0.103:8880 192.168.0.103:8881  192.168.0.103:8882  #集群中其它节点[ip1:port ip2:port ip3:port]
      #JVM调优参数
      #JVM_XMS:  #-Xms default :2g
      #JVM_XMX:  #-Xmx default :2g
      #JVM_XMN:  #-Xmn default :1g
      #JVM_MS:   #-XX:MetaspaceSize default :128m
      #JVM_MMS:  #-XX:MaxMetaspaceSize default :320m
      #NACOS_DEBUG: n #是否开启远程debug，y/n，默认n
      #TOMCAT_ACCESSLOG_ENABLED: true #是否开始tomcat访问日志的记录，默认false
    volumes:
      - ./cluster-logs/nacos1:/home/nacos/logs #日志输出目录
      - ../init.d/custom.properties:/home/nacos/init.d/custom.properties #../init.d/custom.properties内包含很多自定义配置，可按需配置

networks:
  nacos_net:
    driver: bridge