version: '3'
services:
  redis-master:
    container_name: redis-master
    image: redis
    restart: always
    environment:
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/log:/redis/log
  redis-salve:
    image: redis
    container_name: redis-slave
    restart: always
    command: redis-server --slaveof  6379 --port 6380  --requirepass 123456 --masterauth 123456
    ports:
      - 6380:6380
    volumes:
      - ./redis/data:/data
      - ./redis/data:/redis/log
